### ISSUE TITLE
Run fail in window10

### ISSUE THREAD

**Issue by chauhd** [csabapalfi/facebook-scrape-group#3]
Pls help me!

'pgrep' is not recognized as an internal or external command,                                             operable program or batch file.                                                                           npm ERR! code ELIFECYCLE                                                                                  npm ERR! errno 255                                                                                        npm ERR! facebook-group-backup@0.1.0 start: `pgrep Chrome \| xargs kill && node index.js `                 npm ERR! Exit status 255                                                                                  npm ERR!                                                                                                  npm ERR! Failed at the facebook-group-backup@0.1.0 start script.                                          npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                  npm ERR! A complete log of this run can be found in:                                                      npm ERR!     C:\Users\hdchau\AppData\Roaming\npm-cache\_logs\2019-02-14T06_21_44_028Z-debug.log
--

**Comment by csabapalfi** [comment]
Unfortunately this repo only works with MacOS (or simply ported to Linux) but not on Windows.

Sorry about that but I don't normally have access to a Windows machine (apart from browser testing).
